version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    reviewers:
      - "AxonIQ/axoniq-console"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    reviewers:
      - "AxonIQ/axoniq-console"